(function(){
  'use strict';
  const D=window.RoyalBakuData, KEY='rb_bookings_v1', AUTH='rb_admin_session_v2';
  const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const money=v=>`${D.getSettings().currency||'AZN'} ${Number(v||0).toLocaleString()}`;
  const getBookings=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
  const saveBookings=v=>localStorage.setItem(KEY,JSON.stringify(v));
  const loggedIn=()=>sessionStorage.getItem(AUTH)==='1'||localStorage.getItem(AUTH)==='1';
  const logout=()=>{sessionStorage.removeItem(AUTH);localStorage.removeItem(AUTH);localStorage.removeItem('rb_admin_remember_v2');location.href='admin-login.html';};
  if(!loggedIn()){location.replace('admin-login.html');return;}
  let currentTab='overview', modalOpen=false;
  const titles={overview:'Overview',bookings:'Bookings',fleet:'Fleet',tours:'Tours',customers:'Customers',inquiries:'Inquiries',reviews:'Reviews',faqs:'FAQs',content:'Content & Pricing',settings:'Settings'};
  const categories=['sedan','group','suv'];
  const statusList=['Pending','Confirmed','Completed','Cancelled'];

  function imgPicker(id, value){return `<div class="admin-image-picker"><input class="input" id="${id}" name="image" value="${esc(value||'')}" placeholder="https://image-url..."/><input type="file" id="${id}-file" accept="image/*"><small>Paste an image URL or choose a local image. Local images are stored in this browser.</small></div>`}
  function modal(title,html){
    qsa('.admin-modal').forEach(x=>x.remove());const wrap=document.createElement('div');wrap.className='admin-modal';wrap.innerHTML=`<div class="admin-modal-backdrop" data-close-modal></div><div class="admin-modal-card"><div class="admin-modal-head"><div><span class="eyebrow">Royal Baku · Editor</span><h2>${title}</h2></div><button class="admin-modal-close" type="button" data-close-modal>×</button></div>${html}</div>`;document.body.appendChild(wrap);modalOpen=true;
    wrap.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));
    const file=wrap.querySelector('input[type=file]');const image=wrap.querySelector('input[name=image]');file?.addEventListener('change',()=>{const f=file.files?.[0];if(!f||!image)return;const reader=new FileReader();reader.onload=()=>image.value=reader.result;reader.readAsDataURL(f)});
  }
  function closeModal(){qsa('.admin-modal').forEach(x=>x.remove());modalOpen=false;}
  function field(label,name,value='',type='text',extra=''){return `<label class="admin-editor-field"><span>${label}</span><input class="input" name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
  function textarea(label,name,value=''){return `<label class="admin-editor-field"><span>${label}</span><textarea class="input" name="${name}" rows="4">${esc(value)}</textarea></label>`}
  function selectField(label,name,value,opts){return `<label class="admin-editor-field"><span>${label}</span><select class="input" name="${name}">${opts.map(o=>`<option value="${esc(o)}" ${String(value)===String(o)?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`}
  function check(label,name,checked){return `<label class="admin-check"><input type="checkbox" name="${name}" ${checked?'checked':''}><span>${label}</span></label>`}
  function carForm(car={}){
    const f=car.features||[];return `<form id="carEditor" data-id="${esc(car.id||'')}"><div class="editor-grid">${field('Car name','name',car.name)}${field('Category label','category',car.category,'text','required')}${selectField('Fleet type','type',car.type||'sedan',categories)}${field('Daily price','price',car.price||120,'number','min="0" step="1" required')}${field('Weekly price','weekly',car.weekly||0,'number','min="0" step="1"')}${field('Monthly price','monthly',car.monthly||0,'number','min="0" step="1"')}${field('Airport fee','airport',car.airport||0,'number','min="0" step="1"')}${field('Chauffeur fee','chauffeur',car.chauffeur||0,'number','min="0" step="1"')}${field('Seats','seats',car.seats||5,'number','min="1" step="1')}${field('Doors','doors',car.doors||4,'number','min="1" step="1')}${field('Transmission','transmission',car.transmission||'Automatic')}${field('Fuel','fuel',car.fuel||'Petrol')}${field('Color','color',car.color||'Black')}${field('URL/ID slug','id',car.id||('car-'+Date.now()),'text','required')}${field('Service','drive',car.drive||'Self drive / chauffeur')}</div>${field('Blocked rental dates','unavailableDates',Array.isArray(car.unavailableDates)?car.unavailableDates.join(', '):(car.unavailableDates||''),'text','placeholder="2026-09-15, 2026-09-22"')}${textarea('Description','description',car.description||'')}${field('Features (comma separated)','features',f.join(', '))}${imgPicker('carImage',car.image||'')}<div class="editor-checks">${check('Available on website','available',car.available!==false)}${check('Featured vehicle','featured',!!car.featured)}</div><div class="editor-actions"><button type="button" class="btn btn-secondary" data-close-modal>Cancel</button><button class="btn btn-primary" type="submit">Save vehicle ↗</button></div></form>`;
  }
  function tourForm(t={}){return `<form id="tourEditor" data-id="${esc(t.id||'')}"><div class="editor-grid">${field('Tour name','name',t.name)}${field('Category','category',t.category||'City')}${field('Price / person','price',t.price||25,'number','min="0" step="1" required')}${field('Duration','duration',t.duration||'Full day')}${field('Minimum guests','minimum',t.minimum||2,'number','min="1" step="1"')}${field('Tour type','type',t.type||'Group tour')}${field('Focus','focus',t.focus||'Travel')}${field('URL/ID slug','id',t.id||('tour-'+Date.now()),'text','required')}</div>${textarea('Description','description',t.description||'')}${field('Itinerary stops (comma separated)','itinerary',(t.itinerary||[]).join(', '))}${imgPicker('tourImage',t.image||'')}<div class="editor-checks">${check('Available on website','available',t.available!==false)}${check('Featured tour','featured',!!t.featured)}</div><div class="editor-actions"><button type="button" class="btn btn-secondary" data-close-modal>Cancel</button><button class="btn btn-primary" type="submit">Save tour ↗</button></div></form>`}
  function reviewForm(x={}){return `<form id="reviewEditor" data-id="${esc(x.id||'')}">${field('Customer name','name',x.name||'Guest')}${selectField('Rating','rating',x.rating||5,['5','4','3','2','1'])}${textarea('Review','text',x.text||'')}${check('Show on website','active',x.active!==false)}<div class="editor-actions"><button type="button" class="btn btn-secondary" data-close-modal>Cancel</button><button class="btn btn-primary" type="submit">Save review ↗</button></div></form>`}
  function faqForm(x={}){return `<form id="faqEditor" data-id="${esc(x.id||'')}">${field('Question','q',x.q||'')}${textarea('Answer','a',x.a||'')}${check('Show on website','active',x.active!==false)}<div class="editor-actions"><button type="button" class="btn btn-secondary" data-close-modal>Cancel</button><button class="btn btn-primary" type="submit">Save FAQ ↗</button></div></form>`}

  function overview(){const b=getBookings(),cars=D.getCars(),tours=D.getTours(),pending=b.filter(x=>x.status==='Pending').length,confirmed=b.filter(x=>x.status==='Confirmed').length,total=b.filter(x=>x.status!=='Cancelled').reduce((n,x)=>n+Number(x.total||0),0);return `<div class="hero-admin-row"><div><span class="eyebrow">Royal Baku · Command center</span><h2>Manage the business, <span>your way.</span></h2><p>Cars, tours, bookings, pricing, reviews, FAQs and company content can all be edited from this dashboard.</p></div><button class="btn btn-primary" data-switch="fleet">Add / edit fleet ↗</button></div><div class="admin-kpi-grid"><article class="admin-kpi"><span>Cars</span><strong>${cars.length}</strong><small>${cars.filter(c=>c.available!==false).length} visible · ${cars.filter(c=>Array.isArray(c.unavailableDates)&&c.unavailableDates.length).length} with date blocks</small><b class="kpi-icon">🚘</b></article><article class="admin-kpi"><span>Tours</span><strong>${tours.length}</strong><small>${tours.filter(t=>t.available!==false).length} visible</small><b class="kpi-icon">◎</b></article><article class="admin-kpi"><span>Pending</span><strong>${pending}</strong><small>Needs attention</small><b class="kpi-icon warm">!</b></article><article class="admin-kpi"><span>Est. value</span><strong>${money(total)}</strong><small>${confirmed} confirmed requests</small><b class="kpi-icon">₼</b></article></div><div class="admin-grid-2"><section class="admin-card"><div class="admin-card-head"><div><span class="eyebrow">Latest</span><h3>Booking requests</h3></div><button class="text-link" data-switch="bookings">View all ↗</button></div>${bookingRows(b.slice().reverse().slice(0,5))}</section><section class="admin-card"><div class="admin-card-head"><div><span class="eyebrow">Control center</span><h3>Quick edits</h3></div></div><div class="quick-actions"><button data-switch="fleet"><span>🚘</span><div><strong>Manage cars</strong><small>Add, edit, price or hide vehicles</small></div><b>↗</b></button><button data-switch="tours"><span>◎</span><div><strong>Manage tours</strong><small>Edit routes, prices and imagery</small></div><b>↗</b></button><button data-switch="content"><span>⚙</span><div><strong>Pricing & content</strong><small>Extras, contact and business info</small></div><b>↗</b></button></div></section></div>`}
  function statusSelect(b){return `<select class="status-select status-${String(b.status||'Pending').toLowerCase()}" data-status-id="${esc(b.id)}">${statusList.map(s=>`<option ${b.status===s?'selected':''}>${s}</option>`).join('')}</select>`}
  function bookingRows(rows){if(!rows.length)return `<div class="admin-empty"><div class="empty-icon">⌁</div><h3>No requests yet</h3><p>New booking requests will appear here.</p></div>`;return `<div class="table-shell"><table class="admin-table"><thead><tr><th>Request</th><th>Customer</th><th>Item</th><th>Dates</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(b=>{const meta=[b.pickupLocation||b.pickupTime&&('Pickup '+b.pickupTime),b.transport,b.airport].filter(Boolean).join(' · ');return `<tr data-search="${esc([b.id,b.customer,b.phone,b.email,b.item,b.type,b.pickupLocation,b.dropoffLocation].join(' '))}"><td><div class="request-id">${esc(b.id||'RB')}</div><small>${esc(b.type||'Request')} · ${new Date(b.createdAt||Date.now()).toLocaleDateString()}</small></td><td><strong>${esc(b.customer||'Guest')}</strong><small>${esc(b.phone||b.email||'No contact')}</small></td><td><strong>${esc(b.item||'—')}</strong><small>${esc(b.service||b.transport||'')}${meta&&!(b.service||b.transport)?` · ${esc(meta)}`:''}</small></td><td><strong>${esc(b.pickupDate||b.date||'—')}</strong><small>${esc(b.returnDate||b.endDate||'')}</small></td><td><strong>${money(b.total)}</strong></td><td>${statusSelect(b)}</td><td><button class="icon-button" data-book-delete="${esc(b.id)}" title="Delete">×</button></td></tr>`}).join('')}</tbody></table></div>`}

  function getInquiries(){try{return JSON.parse(localStorage.getItem('rb_inquiries_v1')||'[]')}catch{return[]}}
  function saveInquiries(v){localStorage.setItem('rb_inquiries_v1',JSON.stringify(v))}
  function renderInquiries(){const rows=getInquiries().slice().reverse();return `<div class="tab-heading"><div><span class="eyebrow">Customer desk</span><h2>Inquiries</h2><p>Contact form requests saved on this browser.</p></div></div><section class="admin-card"><div class="admin-card-head"><div><span class="eyebrow">Messages</span><h3>Contact requests</h3></div><span class="soft-badge">${rows.length} records</span></div>${rows.length?`<div class="inquiry-list">${rows.map(x=>`<article class="inquiry-item"><div><div class="request-id">${esc(x.id)}</div><h4>${esc(x.subject||'General inquiry')}</h4><p>${esc(x.message||'')}</p><small>${esc(x.name||'Guest')} · ${new Date(x.createdAt).toLocaleString()}</small></div><div class="row-actions"><button class="status-select" data-inquiry-status="${esc(x.id)}">${esc(x.status||'New')}</button><button class="danger-link" data-inquiry-delete="${esc(x.id)}">Delete</button></div></article>`).join('')}</div>`:'<div class="admin-empty"><div class="empty-icon">✉</div><h3>No inquiries yet</h3><p>Contact form messages will appear here.</p></div>'}</section>`}
  function renderBookings(){const b=getBookings().slice().reverse();return `<div class="tab-heading"><div><span class="eyebrow">Operations · Requests</span><h2>Bookings</h2><p>Update status or remove local demo requests.</p></div></div><section class="admin-card"><div class="admin-card-head"><div><span class="eyebrow">Request pipeline</span><h3>All bookings</h3></div><span class="soft-badge">${b.length} records</span></div>${bookingRows(b)}</section>`}
  function renderFleet(){const cars=D.getCars();return `<div class="tab-heading"><div><span class="eyebrow">Operations · Fleet</span><h2>Fleet management</h2><p>Add new vehicles yourself. Changes are saved locally and reflected on the public website.</p></div><button class="btn btn-primary" data-add="car">+ Add new car</button></div><section class="admin-card"><div class="admin-card-head"><div><span class="eyebrow">Editable inventory</span><h3>${cars.length} vehicles</h3></div><span class="soft-badge">Live on this browser</span></div><div class="admin-manage-grid">${cars.map(c=>`<article class="manage-card"><div class="manage-media"><img src="${esc(c.image||'assets/royal-baku-logo.png')}" alt="${esc(c.name)}"><span>${c.available===false?'Hidden':'Live'}</span></div><div class="manage-body"><div><span class="eyebrow">${esc(c.category||'Vehicle')}</span><h3>${esc(c.name)}</h3></div><p>${esc(c.description||'')}</p><div class="manage-meta"><b>${money(c.price)}/day</b><span>${esc(c.seats||'—')} seats · ${esc(c.transmission||'Automatic')}</span></div><div class="manage-actions"><button class="btn btn-secondary" data-edit="car" data-id="${esc(c.id)}">Edit</button><button class="btn btn-secondary" data-duplicate="car" data-id="${esc(c.id)}">Duplicate</button><button class="danger-link" data-delete="car" data-id="${esc(c.id)}">Delete</button></div></div></article>`).join('')}</div></section>`}
  function renderTours(){const tours=D.getTours();return `<div class="tab-heading"><div><span class="eyebrow">Operations · Tourism</span><h2>Tour management</h2><p>Edit your tour products and make new experiences visible on the website.</p></div><button class="btn btn-primary" data-add="tour">+ Add new tour</button></div><section class="admin-card"><div class="admin-manage-grid">${tours.map(t=>`<article class="manage-card"><div class="manage-media"><img src="${esc(t.image||'assets/royal-baku-logo.png')}" alt="${esc(t.name)}"><span>${t.available===false?'Hidden':'Live'}</span></div><div class="manage-body"><div><span class="eyebrow">${esc(t.category||'Tour')}</span><h3>${esc(t.name)}</h3></div><p>${esc(t.description||'')}</p><div class="manage-meta"><b>${money(t.price)}/person</b><span>${esc(t.duration||'Full day')} · min ${esc(t.minimum||2)}</span></div><div class="manage-actions"><button class="btn btn-secondary" data-edit="tour" data-id="${esc(t.id)}">Edit</button><button class="btn btn-secondary" data-duplicate="tour" data-id="${esc(t.id)}">Duplicate</button><button class="danger-link" data-delete="tour" data-id="${esc(t.id)}">Delete</button></div></div></article>`).join('')}</div></section>`}
  function renderCustomers(){const b=getBookings(),m=new Map();b.forEach(x=>{const k=x.phone||x.email||x.customer||'Guest',v=m.get(k)||{name:x.customer||'Guest',phone:x.phone||'—',email:x.email||'—',count:0,total:0};v.count++;v.total+=Number(x.total||0);m.set(k,v)});return `<div class="tab-heading"><div><span class="eyebrow">CRM</span><h2>Customers</h2><p>Customer profiles are derived from booking records.</p></div></div><section class="admin-card"><div class="customer-grid">${[...m.values()].length?[...m.values()].map(x=>`<article class="customer-card"><div class="customer-avatar">${esc(x.name.charAt(0).toUpperCase())}</div><div class="customer-info"><strong>${esc(x.name)}</strong><small>${esc(x.phone)} · ${esc(x.email)}</small></div><div class="customer-stats"><span>${x.count} request${x.count===1?'':'s'}</span><b>${money(x.total)}</b></div></article>`).join(''):'<div class="admin-empty"><h3>No customers yet</h3></div>'}</div></section>`}
  function renderReviews(){const r=D.getReviews();return `<div class="tab-heading"><div><span class="eyebrow">Social proof</span><h2>Reviews</h2><p>Add, edit, hide or delete customer reviews.</p></div><button class="btn btn-primary" data-add="review">+ Add review</button></div><section class="admin-card"><div class="admin-manage-list">${r.map(x=>`<article class="manage-row"><div><div class="rating">${'★'.repeat(Number(x.rating||5))}</div><strong>${esc(x.name)}</strong><p>${esc(x.text)}</p></div><div class="row-actions"><span class="soft-badge">${x.active!==false?'Live':'Hidden'}</span><button class="btn btn-secondary" data-edit="review" data-id="${esc(x.id)}">Edit</button><button class="danger-link" data-delete="review" data-id="${esc(x.id)}">Delete</button></div></article>`).join('')}</div></section>`}
  function renderFaqs(){const r=D.getFaqs();return `<div class="tab-heading"><div><span class="eyebrow">Help center</span><h2>FAQs</h2><p>Keep customer questions and answers current.</p></div><button class="btn btn-primary" data-add="faq">+ Add FAQ</button></div><section class="admin-card"><div class="admin-manage-list">${r.map(x=>`<article class="manage-row"><div><strong>${esc(x.q)}</strong><p>${esc(x.a)}</p></div><div class="row-actions"><span class="soft-badge">${x.active!==false?'Live':'Hidden'}</span><button class="btn btn-secondary" data-edit="faq" data-id="${esc(x.id)}">Edit</button><button class="danger-link" data-delete="faq" data-id="${esc(x.id)}">Delete</button></div></article>`).join('')}</div></section>`}
  function renderContent(){const p=D.getPricing(),s=D.getSettings();return `<div class="tab-heading"><div><span class="eyebrow">Content control</span><h2>Pricing & company content</h2><p>Edit the business information and booking extras used by the customer-facing website.</p></div></div><div class="settings-grid"><section class="admin-card settings-card"><span class="eyebrow">Company details</span><h3>Business information</h3><form id="settingsForm">${field('Business name','businessName',s.businessName)}${field('Phone','phone',s.phone)}${field('WhatsApp','whatsapp',s.whatsapp)}${field('Email','email',s.email)}${textarea('Address','address',s.address)}${field('Opening hours','hours',s.hours)}${field('Currency','currency',s.currency)}<button class="btn btn-primary" type="submit">Save company details ↗</button></form></section><section class="admin-card settings-card"><span class="eyebrow">Booking extras</span><h3>Rental pricing rules</h3><form id="pricingForm">${field('Child seat','childSeat',p.childSeat,'number','min="0"')}${field('Additional driver / day','additionalDriver',p.additionalDriver,'number','min="0"')}${field('Vehicle delivery','delivery',p.delivery,'number','min="0"')}${field('Weekly discount %','weeklyDiscount',p.weeklyDiscount,'number','min="0" max="100"')}${field('Monthly discount %','monthlyDiscount',p.monthlyDiscount,'number','min="0" max="100"')}<button class="btn btn-primary" type="submit">Save pricing ↗</button></form></section></div>`}
  function renderSettings(){return `<div class="tab-heading"><div><span class="eyebrow">Workspace</span><h2>Settings</h2><p>Session controls and local data tools.</p></div></div><div class="settings-grid"><section class="admin-card settings-card"><span class="eyebrow">Access</span><h3>Administrator session</h3><p>This prototype uses browser-based admin login. Production deployment should add server-side authentication and a database.</p><button class="btn btn-secondary" id="logoutFromSettings">Sign out</button></section><section class="admin-card settings-card"><span class="eyebrow">Local data</span><h3>Backup & reset</h3><p>All editable catalog data is stored in localStorage on this browser.</p><div class="hero-actions"><button class="btn btn-secondary" id="exportData">Export JSON</button><button class="btn btn-secondary" id="resetAllData">Restore defaults</button></div></section></div>`}

  function bind(){
    qsa('[data-switch]').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();activate(x.dataset.switch)}));
    qsa('.status-select').forEach(x=>x.addEventListener('change',e=>{const arr=getBookings(),b=arr.find(z=>z.id===e.target.dataset.statusId);if(b){b.status=e.target.value;b.updatedAt=new Date().toISOString();saveBookings(arr);render();activate('bookings',true);}}));
    qsa('[data-inquiry-delete]').forEach(x=>x.addEventListener('click',()=>{if(!confirm('Delete this inquiry?'))return;saveInquiries(getInquiries().filter(i=>i.id!==x.dataset.inquiryDelete));render();activate('inquiries',true)}));
    qsa('[data-inquiry-status]').forEach(x=>x.addEventListener('click',()=>{const arr=getInquiries(),i=arr.find(z=>z.id===x.dataset.inquiryStatus);if(i){i.status=i.status==='New'?'Read':i.status==='Read'?'Replied':'New';saveInquiries(arr);render();activate('inquiries',true)}}));
    qsa('[data-book-delete]').forEach(x=>x.addEventListener('click',()=>{if(!confirm('Delete this booking request?'))return;saveBookings(getBookings().filter(b=>b.id!==x.dataset.bookDelete));render();activate('bookings',true)}));
    qsa('[data-add]').forEach(x=>x.addEventListener('click',()=>{const type=x.dataset.add;if(type==='car')modal('Add new car',carForm());if(type==='tour')modal('Add new tour',tourForm());if(type==='review')modal('Add review',reviewForm());if(type==='faq')modal('Add FAQ',faqForm());bindModalForm();}));
    qsa('[data-edit]').forEach(x=>x.addEventListener('click',()=>{const type=x.dataset.edit,id=x.dataset.id;if(type==='car'){const item=D.getCars().find(c=>c.id===id);modal('Edit vehicle',carForm(item));}if(type==='tour'){const item=D.getTours().find(t=>t.id===id);modal('Edit tour',tourForm(item));}if(type==='review'){const item=D.getReviews().find(t=>t.id===id);modal('Edit review',reviewForm(item));}if(type==='faq'){const item=D.getFaqs().find(t=>t.id===id);modal('Edit FAQ',faqForm(item));}bindModalForm();}));
    qsa('[data-duplicate]').forEach(x=>x.addEventListener('click',()=>{const type=x.dataset.duplicate,id=x.dataset.id;if(type==='car'){const a=D.getCars();const o=a.find(c=>c.id===id);if(!o)return;const n={...o,id:`${o.id}-copy-${Date.now().toString().slice(-4)}`,name:`${o.name} Copy`};a.push(n);D.saveCars(a);render();activate('fleet',true);}else{const a=D.getTours(),o=a.find(t=>t.id===id);if(!o)return;const n={...o,id:`${o.id}-copy-${Date.now().toString().slice(-4)}`,name:`${o.name} Copy`};a.push(n);D.saveTours(a);render();activate('tours',true);}}));
    qsa('[data-delete]').forEach(x=>x.addEventListener('click',()=>{if(!confirm('Delete this item?'))return;const type=x.dataset.delete,id=x.dataset.id;if(type==='car')D.saveCars(D.getCars().filter(c=>c.id!==id));if(type==='tour')D.saveTours(D.getTours().filter(t=>t.id!==id));if(type==='review')D.saveReviews(D.getReviews().filter(r=>r.id!==id));if(type==='faq')D.saveFaqs(D.getFaqs().filter(f=>f.id!==id));render();activate(type==='car'?'fleet':type==='tour'?'tours':type==='review'?'reviews':'faqs',true)}));
    bindModalForm();
    qs('#settingsForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);D.saveSettings(Object.fromEntries(f.entries()));toast('Company details saved');});
    qs('#pricingForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const o={};f.forEach((v,k)=>o[k]=Number(v)||0);D.savePricing(o);toast('Pricing saved');});
    qs('#logoutFromSettings')?.addEventListener('click',logout);
    qs('#exportData')?.addEventListener('click',()=>{const payload={cars:D.getCars(),tours:D.getTours(),reviews:D.getReviews(),faqs:D.getFaqs(),pricing:D.getPricing(),settings:D.getSettings(),bookings:getBookings()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='royal-baku-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
    qs('#resetAllData')?.addEventListener('click',()=>{if(!confirm('Restore all catalog, pricing and company data to defaults?'))return;Object.entries(D.keys).forEach(([k,key])=>localStorage.setItem(key,JSON.stringify(D.defaults[k])));render();activate('settings',true);toast('Defaults restored');});
  }
  function bindModalForm(){const c=qs('#carEditor');if(c&&!c.dataset.bound){c.dataset.bound='1';c.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(c),obj=Object.fromEntries(f.entries());obj.id=obj.id||('car-'+Date.now());obj.price=Number(obj.price)||0;obj.weekly=Number(obj.weekly)||0;obj.monthly=Number(obj.monthly)||0;obj.airport=Number(obj.airport)||0;obj.chauffeur=Number(obj.chauffeur)||0;obj.seats=Number(obj.seats)||5;obj.doors=Number(obj.doors)||4;obj.available=f.get('available')==='on';obj.featured=f.get('featured')==='on';obj.features=String(obj.features||'').split(',').map(x=>x.trim()).filter(Boolean);obj.unavailableDates=String(obj.unavailableDates||'').split(',').map(x=>x.trim()).filter(Boolean);const a=D.getCars(),i=a.findIndex(x=>x.id===c.dataset.id);if(i>=0)a[i]=obj;else a.push(obj);D.saveCars(a);closeModal();render();activate('fleet',true);toast('Vehicle saved');});}
    const t=qs('#tourEditor');if(t&&!t.dataset.bound){t.dataset.bound='1';t.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(t),obj=Object.fromEntries(f.entries());obj.id=obj.id||('tour-'+Date.now());obj.price=Number(obj.price)||0;obj.minimum=Number(obj.minimum)||2;obj.available=f.get('available')==='on';obj.featured=f.get('featured')==='on';obj.itinerary=String(obj.itinerary||'').split(',').map(x=>x.trim()).filter(Boolean);const a=D.getTours(),i=a.findIndex(x=>x.id===t.dataset.id);if(i>=0)a[i]=obj;else a.push(obj);D.saveTours(a);closeModal();render();activate('tours',true);toast('Tour saved');});}
    const r=qs('#reviewEditor');if(r&&!r.dataset.bound){r.dataset.bound='1';r.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(r),obj=Object.fromEntries(f.entries());obj.id=obj.id||('review-'+Date.now());obj.rating=Number(obj.rating)||5;obj.active=f.get('active')==='on';const a=D.getReviews(),i=a.findIndex(x=>x.id===r.dataset.id);if(i>=0)a[i]=obj;else a.push(obj);D.saveReviews(a);closeModal();render();activate('reviews',true);toast('Review saved');});}
    const fq=qs('#faqEditor');if(fq&&!fq.dataset.bound){fq.dataset.bound='1';fq.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(fq),obj=Object.fromEntries(f.entries());obj.id=obj.id||('faq-'+Date.now());obj.active=f.get('active')==='on';const a=D.getFaqs(),i=a.findIndex(x=>x.id===fq.dataset.id);if(i>=0)a[i]=obj;else a.push(obj);D.saveFaqs(a);closeModal();render();activate('faqs',true);toast('FAQ saved');});}
  }
  function toast(text){qsa('.rb-admin-toast').forEach(x=>x.remove());const n=document.createElement('div');n.className='rb-admin-toast';n.textContent=text;document.body.appendChild(n);setTimeout(()=>n.classList.add('show'),20);setTimeout(()=>n.remove(),2200)}
  function render(){qs('#tab-overview').innerHTML=overview();qs('#tab-bookings').innerHTML=renderBookings();qs('#tab-fleet').innerHTML=renderFleet();qs('#tab-tours').innerHTML=renderTours();qs('#tab-customers').innerHTML=renderCustomers();qs('#tab-inquiries').innerHTML=renderInquiries();qs('#tab-reviews').innerHTML=renderReviews();qs('#tab-faqs').innerHTML=renderFaqs();qs('#tab-content').innerHTML=renderContent();qs('#tab-settings').innerHTML=renderSettings();qs('#navPendingBadge').textContent=getBookings().filter(x=>x.status==='Pending').length;const iq=getInquiries();qs('#navInquiryBadge').textContent=iq.filter(x=>x.status==='New').length;bind();}
  function activate(tab,keep=false){currentTab=tab;qsa('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x.dataset.adminTab===tab));qsa('.admin-tab-panel').forEach(p=>p.hidden=p.id!==`tab-${tab}`);qs('#pageTitle').textContent=titles[tab]||'Overview';if(!keep)qs('#adminSidebar')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}
  qs('#logoutAdmin')?.addEventListener('click',logout);qsa('[data-admin-tab]').forEach(x=>x.addEventListener('click',()=>activate(x.dataset.adminTab)));qs('#openSidebar')?.addEventListener('click',()=>qs('#adminSidebar').classList.add('open'));qs('#closeSidebar')?.addEventListener('click',()=>qs('#adminSidebar').classList.remove('open'));qs('#globalSearch')?.addEventListener('input',e=>{const v=e.target.value.toLowerCase().trim();activate('bookings',true);qsa('#tab-bookings tbody tr').forEach(r=>r.style.display=!v||r.dataset.search.toLowerCase().includes(v)?'':'none');});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modalOpen)closeModal()});
  render();activate('overview',true);window.addEventListener('royal-baku-data-change',()=>{render();activate(currentTab,true)});window.addEventListener('storage',e=>{if(e.key==='rb_bookings_v1'||e.key==='rb_inquiries_v1'){render();activate(currentTab,true);toast(e.key==='rb_bookings_v1'?'Bookings updated':'Inquiries updated')}});try{const bc=new BroadcastChannel('royal-baku-bookings');bc.addEventListener('message',e=>{if(e.data?.type==='booking-created'){render();activate(currentTab,true);toast(`New ${String(e.data.booking?.type||'booking').toLowerCase()} received`)}})}catch{}
  try{const ic=new BroadcastChannel('royal-baku-inquiries');ic.addEventListener('message',e=>{if(e.data?.type==='inquiry-created'){render();activate(currentTab,true);toast('New inquiry received')}})}catch{}
})();
