(function(){
'use strict';
const PAGE=(location.pathname.split('/').pop()||'index.html').toLowerCase();
const digits=String(window.RoyalBakuData?.getSettings?.().whatsapp||'994102357434').replace(/\D/g,''); const WA='https://wa.me/'+digits;
const langKey='rb-lang';
const translations={
 en:{home:'Home',fleet:'Fleet',services:'Services',tours:'Tours',contact:'Contact',book:'Book Now',language:'Language',all:'All',sedan:'Sedan',group:'Group',suv:'SUV',search:'Search vehicle',maxPrice:'Max price / day',seats:'Seats',fuel:'Fuel',transmission:'Transmission',results:'vehicles shown',weekly:'Weekly rate',monthly:'Monthly rate',daily:'Daily rate',extras:'Optional extras',plan:'Rental plan',standard:'Standard',step1:'1 · Details',step2:'2 · Options',step3:'3 · Review & send',whatsapp:'Continue to WhatsApp',airport:'Airport pickup',driver:'Chauffeur',child:'Child seat',additional:'Additional driver',delivery:'Vehicle delivery',compare:'Compare',noResults:'No vehicles match these filters.',questions:'Questions, answered'},
 az:{home:'Ana səhifə',fleet:'Avtomobil parkı',services:'Xidmətlər',tours:'Turlar',contact:'Əlaqə',book:'İndi rezerv et',language:'Dil',all:'Hamısı',sedan:'Sedan',group:'Qrup',suv:'SUV',search:'Avtomobil axtar',maxPrice:'Maks. günlük qiymət',seats:'Oturacaq',fuel:'Yanacaq',transmission:'Sürətlər qutusu',results:'avtomobil göstərilir',weekly:'Həftəlik tarif',monthly:'Aylıq tarif',daily:'Günlük tarif',extras:'Əlavə seçimlər',plan:'İcarə planı',standard:'Standart',step1:'1 · Məlumat',step2:'2 · Seçimlər',step3:'3 · Yoxla və göndər',whatsapp:'WhatsApp-a davam et',airport:'Aeroport transferi',driver:'Sürücü',child:'Uşaq oturacağı',additional:'Əlavə sürücü',delivery:'Avtomobil çatdırılması',compare:'Müqayisə et',noResults:'Bu filtrlərə uyğun avtomobil tapılmadı.',questions:'Suallar və cavablar'},
 ru:{home:'Главная',fleet:'Автопарк',services:'Услуги',tours:'Туры',contact:'Контакты',book:'Забронировать',language:'Язык',all:'Все',sedan:'Седан',group:'Для группы',suv:'SUV',search:'Поиск автомобиля',maxPrice:'Макс. цена / день',seats:'Мест',fuel:'Топливо',transmission:'Коробка',results:'автомобилей показано',weekly:'Недельный тариф',monthly:'Месячный тариф',daily:'Дневной тариф',extras:'Дополнительные услуги',plan:'План аренды',standard:'Стандарт',step1:'1 · Данные',step2:'2 · Опции',step3:'3 · Проверка и отправка',whatsapp:'Продолжить в WhatsApp',airport:'Трансфер из аэропорта',driver:'С водителем',child:'Детское кресло',additional:'Доп. водитель',delivery:'Доставка автомобиля',compare:'Сравнить',noResults:'Автомобили по этим фильтрам не найдены.',questions:'Вопросы и ответы'},
 ur:{home:'ہوم',fleet:'فلیٹ',services:'سروسز',tours:'ٹورز',contact:'رابطہ',book:'اب بک کریں',language:'زبان',all:'تمام',sedan:'سیڈان',group:'گروپ',suv:'SUV',search:'گاڑی تلاش کریں',maxPrice:'زیادہ سے زیادہ قیمت / دن',seats:'سیٹس',fuel:'ایندھن',transmission:'ٹرانسمیشن',results:'گاڑیاں دکھائی گئی ہیں',weekly:'ہفتہ وار ریٹ',monthly:'ماہانہ ریٹ',daily:'روزانہ ریٹ',extras:'اضافی آپشنز',plan:'رینٹل پلان',standard:'اسٹینڈرڈ',step1:'1 · معلومات',step2:'2 · آپشنز',step3:'3 · جائزہ اور ارسال',whatsapp:'WhatsApp پر جاری رکھیں',airport:'ایئرپورٹ پک اپ',driver:'ڈرائیور',child:'چائلڈ سیٹ',additional:'اضافی ڈرائیور',delivery:'گاڑی ڈیلیوری',compare:'موازنہ',noResults:'ان فلٹرز کے مطابق کوئی گاڑی نہیں ملی۔',questions:'سوالات اور جوابات'}
};
function t(k){const l=localStorage.getItem(langKey)||'en';return (translations[l]||translations.en)[k]||translations.en[k]||k}
function addLang(){
 const nav=document.querySelector('.nav');
 const navLinks=document.querySelector('.nav-links');
 if(!nav||!navLinks||document.querySelector('.rb-utility'))return;
 const wrap=document.createElement('div');
 wrap.className='rb-utility';
 wrap.innerHTML='<span class="rb-language-label">Language</span><select class="rb-select" aria-label="Language"><option value="en">EN</option><option value="az">AZ</option><option value="ru">RU</option><option value="ur">UR</option></select>';
 // Keep the language control inside the navigation row so it never floats over Book Now.
 const cta=navLinks.querySelector('.nav-cta');
 if(cta) navLinks.insertBefore(wrap,cta);
 else navLinks.appendChild(wrap);
 const s=wrap.querySelector('select');
 s.value=localStorage.getItem(langKey)||'en';
 s.addEventListener('change',()=>{localStorage.setItem(langKey,s.value);applyCommonLanguage();});
}
function applyCommonLanguage(){
 const l=localStorage.getItem(langKey)||'en'; document.documentElement.lang=l;
 const navMap=[['index.html','home'],['fleet.html','fleet'],['services.html','services'],['tours.html','tours'],['contact.html','contact']];
 document.querySelectorAll('.nav-links a, .mobile-menu-inner a').forEach(a=>{const h=(a.getAttribute('href')||'').split('?')[0];const m=navMap.find(x=>h===x[0]);if(m&&!a.classList.contains('nav-cta'))a.textContent=t(m[1]); if(a.classList.contains('nav-cta'))a.textContent=t('book');}); document.querySelectorAll('.rb-select').forEach(x=>{x.value=l});
 document.querySelectorAll('[data-filter="all"]').forEach(x=>x.textContent=t('all')); document.querySelectorAll('[data-filter="sedan"]').forEach(x=>x.textContent=t('sedan')); document.querySelectorAll('[data-filter="group"]').forEach(x=>x.textContent=t('group')); document.querySelectorAll('[data-filter="suv"]').forEach(x=>x.textContent=t('suv'));
 document.querySelectorAll('.whatsapp-btn span:first-of-type').forEach(x=>x.textContent=t('whatsapp'));
 document.querySelectorAll('.compare-toggle').forEach(x=>{if(!x.classList.contains('compare-selected'))x.textContent='＋ '+t('compare');});
}
window.applyCommonLanguage=applyCommonLanguage;
function addHomeUX(){
 if(PAGE!=='index.html')return;const main=document.querySelector('main');if(!main||document.querySelector('.rb-home-upgrade'))return;
 const sec=document.createElement('section');sec.className='section rb-home-upgrade';sec.innerHTML=`<div class="container"><div class="rb-kicker-bar"><div class="rb-kicker"><b>Airport arrivals</b><span>Pickup coordination in Baku</span></div><div class="rb-kicker"><b>Self drive</b><span>Flexible daily rental options</span></div><div class="rb-kicker"><b>Chauffeur</b><span>Professional driver service</span></div><div class="rb-kicker"><b>Tour planning</b><span>City, mountain & nature routes</span></div></div><div class="rb-feature-row"><div class="rb-feature-pill"><i class="fa-solid fa-shield-halved"></i><b>Clear booking flow</b><span>Review the estimate before opening WhatsApp.</span></div><div class="rb-feature-pill"><i class="fa-solid fa-clock"></i><b>Daily contact window</b><span>Royal Baku: 09:00 AM – 09:00 PM.</span></div><div class="rb-feature-pill"><i class="fa-solid fa-location-dot"></i><b>Central Baku office</b><span>Khagani Mall, Nizami Street.</span></div><div class="rb-feature-pill"><i class="fa-brands fa-whatsapp"></i><b>Direct WhatsApp</b><span>Send a request without online payment.</span></div></div></div>`;
 const first=main.querySelector('.section'); if(first)first.insertAdjacentElement('afterend',sec); else main.appendChild(sec);
}
function enhanceFleet(){
 if(PAGE!=='fleet.html')return; const host=document.querySelector('.fleet-filter');const grid=document.querySelector('.fleet-grid');if(!host||!grid||document.querySelector('.rb-fleet-tools'))return;
 const tools=document.createElement('div');tools.className='rb-fleet-tools';tools.innerHTML=`<div class="rb-tool-search"><label class="rb-filter-label">${t('search')}</label><input class="input" id="rbFleetSearch" placeholder="Mercedes, Kia, Range Rover..." /></div><div><label class="rb-filter-label">${t('maxPrice')}</label><select class="input" id="rbFleetPrice"><option value="all">Any</option><option value="100">≤ 100 AZN</option><option value="130">≤ 130 AZN</option><option value="160">≤ 160 AZN</option><option value="220">≤ 220 AZN</option></select></div><div><label class="rb-filter-label">${t('seats')}</label><select class="input" id="rbFleetSeats"><option value="all">Any</option><option value="5">5+</option><option value="8">8+</option></select></div><div><label class="rb-filter-label">${t('fuel')}</label><select class="input" id="rbFleetFuel"><option value="all">Any</option><option>Petrol</option><option>Diesel</option></select></div><div><label class="rb-filter-label">${t('transmission')}</label><select class="input" id="rbFleetTransmission"><option value="all">Any</option><option>Automatic</option></select></div>`;
 host.insertAdjacentElement('afterend',tools); const note=document.createElement('div');note.className='rb-results-note';note.id='rbFleetNote';grid.parentElement.insertBefore(note,grid);
 const no=document.createElement('div');no.className='rb-no-results';no.id='rbNoResults';no.innerHTML=`<b>${t('noResults')}</b><br><span>Try a wider price range or clear a filter.</span>`;grid.insertAdjacentElement('afterend',no);
 const cards=[...grid.querySelectorAll('.fleet-card')]; const run=()=>{const q=(document.getElementById('rbFleetSearch').value||'').trim().toLowerCase();const p=document.getElementById('rbFleetPrice').value;const s=document.getElementById('rbFleetSeats').value;const f=document.getElementById('rbFleetFuel').value;const tr=document.getElementById('rbFleetTransmission').value;let count=0;cards.forEach(c=>{const ok=(!q||c.dataset.vehicle.toLowerCase().includes(q))&&(p==='all'||Number(c.dataset.price)<=Number(p))&&(s==='all'||Number(c.dataset.seats)>=Number(s))&&(f==='all'||c.dataset.fuel===f)&&(tr==='all'||c.dataset.transmission===tr);c.hidden=!ok;if(!ok){c.classList.remove('is-open');c.setAttribute('aria-expanded','false')}if(ok)count++});note.innerHTML=`<b>${count}</b> ${t('results')} · Sorted from the displayed starting prices`;no.style.display=count?'none':'block';};
 tools.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',run));tools.querySelectorAll('select').forEach(x=>x.addEventListener('change',run));document.querySelectorAll('.filter').forEach(x=>x.addEventListener('click',()=>setTimeout(run,0)));run();
 const price=document.createElement('div');price.className='rb-pricing-band';price.innerHTML=`<div class="rb-price-card"><span>${t('daily')}</span><strong>1 day</strong><span>Displayed starting price</span></div><div class="rb-price-card"><span>${t('weekly')}</span><strong>−10%</strong><span>Illustrative multi-day saving; final quote confirmed by Royal Baku</span></div><div class="rb-price-card"><span>${t('monthly')}</span><strong>−18%</strong><span>Illustrative long-stay saving; final quote confirmed by Royal Baku</span></div>`;grid.insertAdjacentElement('afterend',price);
}
const carMeta=Object.fromEntries((window.RoyalBakuData?.getCars?.()||[]).map(c=>[c.id,c]));
function enhanceBookingPage(){
 if(!['booking.html','tour-booking.html'].includes(PAGE))return;
 const form=document.querySelector('form');if(!form)return;
 const steps=document.createElement('div');steps.className='rb-book-steps';steps.innerHTML=`<div class="rb-book-step active"><b>${t('step1')}</b><span>Dates, guest & pickup</span></div><div class="rb-book-step"><b>${t('step2')}</b><span>${t('extras')} & service</span></div><div class="rb-book-step"><b>${t('step3')}</b><span>${t('standard')} summary + WhatsApp</span></div>`;form.insertBefore(steps,form.firstChild);
 if(PAGE==='booking.html'){
  const serviceField=form.querySelector('input[name="service"]')?.closest('.field');const quote=form.querySelector('.quote');
  if(serviceField){const pr=window.RoyalBakuData?.getPricing?.()||{childSeat:10,additionalDriver:15,delivery:20};const extra=document.createElement('div');extra.className='field';extra.innerHTML=`<label>${t('extras')}</label><div class="rb-extras"><label class="rb-extra"><input type="checkbox" name="rb_extra_child" data-fee="${pr.childSeat}"><span><b>${t('child')}</b><span>AZN ${pr.childSeat} / rental</span></span></label><label class="rb-extra"><input type="checkbox" name="rb_extra_driver" data-fee="${pr.additionalDriver}"><span><b>${t('additional')}</b><span>AZN ${pr.additionalDriver} / day</span></span></label><label class="rb-extra"><input type="checkbox" name="rb_extra_delivery" data-fee="${pr.delivery}"><span><b>${t('delivery')}</b><span>AZN ${pr.delivery} one way</span></span></label></div>`;serviceField.insertAdjacentElement('afterend',extra);}
  if(quote){const plan=document.createElement('div');plan.className='field';plan.innerHTML=`<label>${t('plan')}</label><div class="rb-plan-grid"><label class="rb-plan active"><input type="radio" name="rb_plan" value="daily" data-discount="0" checked><b>${t('daily')}</b><span>0% discount</span></label><label class="rb-plan"><input type="radio" name="rb_plan" value="weekly" data-discount="${Number((window.RoyalBakuData?.getPricing?.()||{}).weeklyDiscount||10)/100}"><b>${t('weekly')}</b><span>${Number((window.RoyalBakuData?.getPricing?.()||{}).weeklyDiscount||10)}% illustrative saving</span></label><label class="rb-plan"><input type="radio" name="rb_plan" value="monthly" data-discount="${Number((window.RoyalBakuData?.getPricing?.()||{}).monthlyDiscount||18)/100}"><b>${t('monthly')}</b><span>${Number((window.RoyalBakuData?.getPricing?.()||{}).monthlyDiscount||18)}% illustrative saving</span></label></div>`;quote.insertAdjacentElement('beforebegin',plan);}
  const sync=()=>{const days=Math.max(1,Number((document.getElementById('qDays')?.textContent||1)));const daily=(Number((document.getElementById('qRental')?.textContent||'').replace(/[^0-9.]/g,''))/days)||120;const disc=Number(document.querySelector('input[name="rb_plan"]:checked')?.dataset.discount||0);let rental=Math.round(days*daily*(1-disc));const airport=Number((document.getElementById('qAirport')?.textContent||'').replace(/[^0-9.]/g,''))||0;const driver=Number((document.getElementById('qDriver')?.textContent||'').replace(/[^0-9.]/g,''))||0;let extra=0;document.querySelectorAll('[name^="rb_extra_"]:checked').forEach(x=>extra+=Number(x.dataset.fee||0)*(x.name==='rb_extra_driver'?days:1));document.getElementById('qRental').textContent=`AZN ${rental}`;let er=form.querySelector('#rbExtrasTotal');if(!er){er=document.createElement('div');er.className='quote-line';er.id='rbExtrasTotal';document.querySelector('.quote .total')?.before(er)}er.innerHTML=`<span>Extras</span><b>AZN ${extra}</b>`;document.getElementById('qTotal').textContent=`AZN ${rental+airport+driver+extra}`;document.querySelectorAll('.rb-plan').forEach(x=>x.classList.toggle('active',x.querySelector('input').checked));return {days,rental,airport,driver,extra,total:rental+airport+driver+extra};};
  form.querySelectorAll('input,select,textarea').forEach(x=>x.addEventListener('change',()=>setTimeout(sync,0)));form.querySelectorAll('input').forEach(x=>x.addEventListener('input',()=>setTimeout(sync,0)));sync();
  form.addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();const q=sync();const carKey=new URLSearchParams(location.search).get('car')||'c300';const car=carMeta[carKey]||carMeta[Object.keys(carMeta)[0]]; if(!car)return;const service=document.querySelector('input[name="service"]:checked')?.value||'Self drive';const airport=document.querySelector('input[name="airport"]:checked')?.value||'No airport transfer';const extras=[...form.querySelectorAll('[name^="rb_extra_"]:checked')].map(x=>x.closest('label')?.innerText.trim().replace(/\n+/g,' — ')).join(', ')||'None';const msg=[`ROYAL BAKU — CAR BOOKING REQUEST`,``,`Vehicle: ${car.name}`,`Service: ${service}`,`Pickup: ${document.getElementById('pickupDate').value} at ${document.getElementById('pickupTime').value}`,`Return: ${document.getElementById('dropoffDate').value}`,`Pickup location: ${document.getElementById('pickupLocation').value}`,`Drop-off: ${document.getElementById('dropoffLocation').value||'To be confirmed'}`,`Airport: ${airport}`,`Extras: ${extras}`,``,`Guest: ${document.getElementById('name').value}`,`WhatsApp: ${document.getElementById('phone').value}`,`Notes: ${document.getElementById('notes').value||'—'}`,``,`Estimated total: AZN ${q.total}`,`Plan: ${document.querySelector('input[name="rb_plan"]:checked')?.value||'daily'}`,``,`Please confirm availability and final quote.`].join('\n');const id='RB-'+Date.now().toString().slice(-6);localStorage.setItem('rb_last_booking_id',id);const records=JSON.parse(localStorage.getItem('rb_bookings_v1')||'[]');records.push({id,type:'Rental',customer:document.getElementById('name').value,phone:document.getElementById('phone').value,email:'',item:car.name,carId:car.id,pickupDate:document.getElementById('pickupDate').value,returnDate:document.getElementById('dropoffDate').value,total:q.total,status:'Pending',createdAt:new Date().toISOString(),service,airport,extras,notes:document.getElementById('notes').value||''});localStorage.setItem('rb_bookings_v1',JSON.stringify(records));document.getElementById('bookingSuccess').classList.add('show');window.open(WA+'?text='+encodeURIComponent(msg),'_blank','noopener,noreferrer');},{capture:true});
 }
}
function enhanceTours(){
 if(PAGE!=='tours.html')return;const cards=[...document.querySelectorAll('.tour-card')];cards.forEach(c=>{if(c.querySelector('.rb-tour-itinerary'))return;const key=c.dataset.tour||'baku';const stops={baku:['Old City','Boulevard','Modern Baku'],sheki:['Sheki center','Cultural stops','Scenic viewpoints'],shahdag:['Mountain route','Shahdag area','Photo stops'],gabala:['Lake views','Nature stops','Local highlights']}[key]||[];const d=document.createElement('div');d.className='rb-tour-itinerary';d.innerHTML=stops.map((s,i)=>`<div class="rb-tour-stop"><small>0${i+1}</small><b>${s}</b></div>`).join('');c.querySelector('.tour-details')?.insertBefore(d,c.querySelector('.tour-details').firstChild);});
}
function enhanceContact(){
 if(PAGE!=='contact.html')return;const form=document.querySelector('.form');if(!form||document.querySelector('.rb-contact-quick'))return;const q=document.createElement('div');q.className='rb-contact-quick';const liveDigits=String(window.RoyalBakuData?.getSettings?.().whatsapp||'994102357434').replace(/\D/g,'');q.innerHTML=`<div class="eyebrow">Quick choices</div><div class="hero-actions" style="margin-top:10px"><a class="btn btn-secondary" href="fleet.html">Explore fleet</a><a class="btn btn-secondary" href="tours.html">Explore tours</a><a class="btn btn-primary" href="https://wa.me/${liveDigits}?text=Hello%20Royal%20Baku%2C%20I%20need%20airport%20pickup." target="_blank" rel="noopener">Airport pickup</a></div>`;form.insertAdjacentElement('afterend',q);
}
function addSchema(){
 if(document.querySelector('#rb-schema'))return;const s=document.createElement('script');s.type='application/ld+json';s.id='rb-schema';s.textContent=JSON.stringify({"@context":"https://schema.org","@type":"AutoRental","name":"Royal Baku Car Rental & Tourism","telephone":"+994 10 235 7434","address":{"@type":"PostalAddress","streetAddress":"Office No. 09, 3rd Floor, Khagani Mall, Nizami Street","addressLocality":"Baku","addressCountry":"AZ"},"openingHours":"Mo-Su 09:00-21:00","url":location.href});document.head.appendChild(s);
}
function guardDates(){['booking.html','tour-booking.html'].includes(PAGE)&&document.querySelectorAll('input[type=date]').forEach(x=>{const today=new Date();const v=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);if(!x.min)x.min=v});}
function boot(){addLang();applyCommonLanguage();addHomeUX();enhanceFleet();enhanceBookingPage();enhanceTours();enhanceContact();addSchema();guardDates();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
