(function(){
  'use strict';
  const KEYS={cars:'rb_cars_v1',tours:'rb_tours_v1',reviews:'rb_reviews_v1',faqs:'rb_faqs_v1',pricing:'rb_pricing_v1',settings:'rb_settings_v1'};
  const defaults={
    cars:[
      {id:'c300',name:'Mercedes C300',category:'Executive sedan',type:'sedan',price:120,weekly:756,monthly:2952,airport:35,chauffeur:80,seats:5,doors:4,transmission:'Automatic',fuel:'Petrol',color:'Black',drive:'Self drive / chauffeur',description:'Elegant city performance with a premium executive cabin, ideal for business trips and luxury Baku drives.',image:'https://images.pexels.com/photos/15535501/pexels-photo-15535501.jpeg?cs=srgb&dl=pexels-453707837-15535501.jpg&fm=jpg',features:['Leather interior','Apple CarPlay','Air conditioning'],available:true,featured:true},
      {id:'cla250',name:'Mercedes CLA 250',category:'Sport sedan',type:'sedan',price:110,weekly:693,monthly:2706,airport:35,chauffeur:75,seats:5,doors:4,transmission:'Automatic',fuel:'Petrol',color:'White',drive:'Self drive / chauffeur',description:'Low-slung styling, premium comfort and a sporty presence for sophisticated city travel.',image:'https://images.pexels.com/photos/10907355/pexels-photo-10907355.jpeg?cs=srgb&dl=pexels-niclas-haritos-1133747-10907355.jpg&fm=jpg',features:['Premium cabin','Parking sensors','Bluetooth'],available:true,featured:true},
      {id:'vito',name:'Mercedes Vito',category:'Premium van',type:'group',price:150,weekly:945,monthly:3690,airport:45,chauffeur:95,seats:8,doors:4,transmission:'Automatic',fuel:'Diesel',color:'Black',drive:'Self drive / chauffeur',description:'Comfort-first people mover for airport transfers, families, corporate teams and group touring.',image:'https://images.pexels.com/photos/31040129/pexels-photo-31040129.jpeg?cs=srgb&dl=pexels-vishal-makwana-2146804431-31040129.jpg&fm=jpg',features:['8 seats','Large luggage space','Rear climate'],available:true,featured:false},
      {id:'carnival',name:'Kia Carnival',category:'Family MPV',type:'group',price:140,weekly:882,monthly:3444,airport:45,chauffeur:90,seats:8,doors:4,transmission:'Automatic',fuel:'Petrol',color:'White',drive:'Self drive / chauffeur',description:'Spacious family comfort with easy access, generous cabin space and long-day touring capability.',image:'https://images.pexels.com/photos/7762710/pexels-photo-7762710.jpeg?cs=srgb&dl=pexels-mike-bird-170811-7762710.jpg&fm=jpg',features:['8 seats','Family friendly','Large cabin'],available:true,featured:false},
      {id:'optima',name:'Kia Optima',category:'Executive value',type:'sedan',price:90,weekly:567,monthly:2214,airport:30,chauffeur:70,seats:5,doors:4,transmission:'Automatic',fuel:'Petrol',color:'Black',drive:'Self drive / chauffeur',description:'A comfortable, polished daily rental for guests who want reliable premium mobility around Baku.',image:'https://images.pexels.com/photos/15171354/pexels-photo-15171354.jpeg?cs=srgb&dl=pexels-isaac-mitchell-278678383-15171354.jpg&fm=jpg',features:['Comfort seats','Reliable daily use','Climate control'],available:true,featured:false},
      {id:'range-rover-sport',name:'Range Rover Sport',category:'Luxury SUV',type:'suv',price:220,weekly:1386,monthly:5412,airport:50,chauffeur:120,seats:5,doors:5,transmission:'Automatic',fuel:'Petrol',color:'Black',drive:'Self drive / chauffeur',description:'Commanding SUV presence with a premium cabin and confident road stance for VIP city and touring use.',image:'https://images.pexels.com/photos/7762710/pexels-photo-7762710.jpeg?cs=srgb&dl=pexels-mike-bird-170811-7762710.jpg&fm=jpg',features:['Luxury interior','SUV capability','Premium sound'],available:true,featured:true}
    ],
    tours:[
      {id:'baku',name:'Baku City Tour',category:'City',price:25,duration:'Full day',minimum:2,type:'Group tour',focus:'City & culture',image:'https://images.pexels.com/photos/31617733/pexels-photo-31617733.jpeg?cs=srgb&dl=pexels-abdurrahim-israfilov-15171262-31617733.jpg&fm=jpg',description:'Discover the beauty, culture and modern attractions of Baku with a comfortable city-focused itinerary.',itinerary:['Old City','Boulevard','Modern Baku'],featured:true,available:true},
      {id:'sheki',name:'Sheki City Tour',category:'Best seller',price:45,duration:'Full day',minimum:2,type:'Group tour',focus:'Culture & nature',image:'https://images.pexels.com/photos/1470405/pexels-photo-1470405.jpeg?auto=compress&cs=tinysrgb&w=1200',description:'Scenic beauty, culture and landmarks.',itinerary:['Sheki center','Cultural stops','Scenic viewpoints'],featured:true,available:true},
      {id:'shahdag',name:'Shahdag Tour',category:'Mountains',price:40,duration:'Full day',minimum:2,type:'Group tour',focus:'Mountains',image:'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg?auto=compress&cs=tinysrgb&w=1200',description:'Beautiful mountains and open nature.',itinerary:['Mountain route','Shahdag area','Photo stops'],featured:false,available:true},
      {id:'gabala',name:'Gabala Tour',category:'Nature',price:40,duration:'Full day',minimum:2,type:'Group tour',focus:'Nature',image:'https://images.pexels.com/photos/1535162/pexels-photo-1535162.jpeg?auto=compress&cs=tinysrgb&w=1200',description:'Mountains, lakes and natural attractions.',itinerary:['Lake views','Nature stops','Local highlights'],featured:false,available:true}
    ],
    reviews:[
      {id:'r1',name:'Verified guest',rating:5,text:'Professional service, smooth pickup and a comfortable vehicle.',active:true},
      {id:'r2',name:'Business traveller',rating:5,text:'Easy communication and a premium experience in Baku.',active:true},
      {id:'r3',name:'Family guest',rating:5,text:'The vehicle was clean, spacious and perfect for our Azerbaijan trip.',active:true}
    ],
    faqs:[
      {id:'f1',q:'Can I book through WhatsApp?',a:'Yes. The website prepares your request and opens WhatsApp for direct confirmation.',active:true},
      {id:'f2',q:'Do you offer airport pickup?',a:'Yes. Airport pickup and drop-off can be requested during booking.',active:true},
      {id:'f3',q:'Can I request a chauffeur?',a:'Yes. Chauffeur service is available on selected vehicles and can be requested in the booking flow.',active:true}
    ],
    pricing:{childSeat:10,additionalDriver:15,delivery:20,weeklyDiscount:10,monthlyDiscount:18},
    settings:{businessName:'Royal Baku Car Rental & Tourism',phone:'+994 10 235 7434',whatsapp:'+994 10 235 7434',email:'',address:'Office No. 09, 3rd Floor, Khagani Mall, Nizami Street, Baku, Azerbaijan',hours:'09:00 AM – 09:00 PM',currency:'AZN'}
  };
  function read(key){try{const v=JSON.parse(localStorage.getItem(KEYS[key])||'null');return v===null?JSON.parse(JSON.stringify(defaults[key])):v}catch{return JSON.parse(JSON.stringify(defaults[key]))}}
  function write(key,val){localStorage.setItem(KEYS[key],JSON.stringify(val));window.dispatchEvent(new CustomEvent('royal-baku-data-change',{detail:{key,val}}));return val}
  function isDateBlocked(car,date){return Array.isArray(car?.unavailableDates)&&car.unavailableDates.includes(date)}
  Object.keys(KEYS).forEach(k=>{if(localStorage.getItem(KEYS[k])===null)write(k,defaults[k]);});
  window.RoyalBakuData={keys:KEYS,defaults,getCars:()=>read('cars'),saveCars:v=>write('cars',v),getTours:()=>read('tours'),saveTours:v=>write('tours',v),getReviews:()=>read('reviews'),saveReviews:v=>write('reviews',v),getFaqs:()=>read('faqs'),saveFaqs:v=>write('faqs',v),getPricing:()=>read('pricing'),savePricing:v=>write('pricing',v),getSettings:()=>read('settings'),saveSettings:v=>write('settings',v),isDateBlocked};
})();
